sensors:
  - default_sensor
default_sensor:
  filtered_cloud_topic: filtered_cloud
  max_range: 10.0
  max_update_rate: 1.0
  padding_offset: 0.1
  padding_scale: 1.0
  point_cloud_topic: /realsense/points
  point_subsample: 1
  sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
  far_clipping_plane_distance: 5.0
  near_clipping_plane_distance: 0.1
  queue_size: 1
  shadow_threshold: 0.1
